(function(){
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), list=a=>`<ul>${(Array.isArray(a)?a:[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`, KEY='ts_last_vocal_map';
try{const d=JSON.parse(localStorage.getItem('ts_vocal_draft')||localStorage.getItem('ts_promotion_draft')||'{}');['title','lyrics','genre','mood','vocalType'].forEach(k=>{if(d[k])$(k).value=d[k]})}catch{}
function payload(){return{title:$('title').value.trim(),lyrics:$('lyrics').value.trim(),genre:$('genre').value.trim(),mood:$('mood').value.trim(),vocalType:$('vocalType').value.trim(),experience:$('experience').value,planToken:localStorage.getItem('ts_plan_token')||''}}
function marked(line){let text=esc(line?.text);(line?.accentWords||[]).sort((a,b)=>b.length-a.length).forEach(w=>{if(w)text=text.replace(esc(w),`<mark>${esc(w)}</mark>`)});return`<div class="lyric-line">${text}${line?.note?`<small>↳ ${esc(line.note)}</small>`:''}</div>`}
function render(saved){const d=saved.result||{},dna=d.dna||{},names={energy:'Энергия',emotion:'Эмоции',intimacy:'Интимность',softness:'Мягкость',drama:'Драматизм'};
const cards=Object.entries(names).map(([k,n])=>`<div class="dna-card"><strong>${Math.max(0,Math.min(100,+dna[k]||0))}%</strong><span>${n}</span></div>`).join('');
const sections=(d.sections||[]).map(s=>`<div class="section-card"><div><strong>${esc(s.name)}</strong><div class="energy"><i style="width:${Math.max(0,Math.min(100,+s.energy||0))}%"></i></div><small>${esc(s.energy)}% энергии</small></div><div><strong>${esc(s.emotion)}</strong><p>${esc(s.delivery)}</p><small>${esc(s.focus)}</small></div></div>`).join('');
const lyrics=(d.markedLyrics||[]).map(b=>`<div class="lyric-block"><h3>${esc(b.section)}</h3><div class="direction">${esc(b.direction)}</div>${(b.lines||[]).map(marked).join('')}</div>`).join('');
$('result').innerHTML=`<header class="result-header"><div class="eyebrow"><span class="dot"></span>карта исполнения TrackStart</div><h1>${esc(saved.input?.title)}</h1><p>Творческие ориентиры по тексту — адаптируйте их под свой голос и мелодию.</p></header><div class="result-actions no-print"><button class="btn btn-primary" id="copy-vocal">Скопировать всё</button><button class="btn btn-secondary" id="print-vocal">Сохранить PDF</button><button class="btn btn-secondary" id="edit-vocal">Изменить данные</button></div><section class="result-section"><h2>1. Образ исполнения</h2><p>${esc(d.concept)}</p><h3>Рекомендуемый характер тембра</h3><div class="tag-list">${(d.tone||[]).map(v=>`<span>${esc(v)}</span>`).join('')}</div><h3>Главные правила</h3>${list(d.rules)}<div class="dna-grid">${cards}</div></section><section class="result-section"><h2>2. Карта песни</h2>${sections}</section><section class="result-section"><h2>3. Размеченный текст</h2>${lyrics}</section><section class="result-section"><h2>4. Перед записью</h2>${list(d.beforeRecording)}<h3>Чего избегать</h3>${list(d.avoid)}</section><section class="result-section"><div class="coach"><h2>Комментарий продюсера</h2><p>${esc(d.coach)}</p></div></section>`;
$('form-wrap').hidden=true;$('loading').hidden=true;$('error').hidden=true;$('result').hidden=false;
$('copy-vocal').onclick=async()=>{await navigator.clipboard.writeText($('result').innerText.replace(/Скопировать всё\s+Сохранить PDF\s+Изменить данные/,'').trim());$('copy-vocal').textContent='✓ Скопировано'};$('print-vocal').onclick=()=>print();$('edit-vocal').onclick=()=>{$('result').hidden=true;$('form-wrap').hidden=false;scrollTo({top:0,behavior:'smooth'})}}
$('vocal-form').addEventListener('submit',async e=>{e.preventDefault();const p=payload(),btn=$('generate-vocal');$('form-wrap').hidden=true;$('error').hidden=true;$('loading').hidden=false;btn.disabled=true;try{const r=await fetch('/api/vocal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}),b=await r.json().catch(()=>({}));if(!r.ok||!b.result){const err=new Error(b.error||'Не удалось создать карту');err.code=b.code;throw err}const saved={input:{...p,planToken:undefined},result:b.result,generatedAt:b.generatedAt};localStorage.setItem(KEY,JSON.stringify(saved));render(saved)}catch(err){$('loading').hidden=true;$('form-wrap').hidden=false;if(err.code==='PRO_REQUIRED')$('error').innerHTML='<strong>Пробная карта уже использована.</strong><br>Новые карты исполнения доступны на тарифе Pro.<br><a class="btn btn-primary" href="index.html#pricing" style="margin-top:16px">Подключить Pro</a>';else $('error').textContent=err.message;$('error').hidden=false}finally{btn.disabled=false}});
$('restore-vocal').onclick=()=>{try{render(JSON.parse(localStorage.getItem(KEY)))}catch{localStorage.removeItem(KEY);$('restore-vocal').hidden=true}};if(localStorage.getItem(KEY))$('restore-vocal').hidden=false;
})();
